import type { Place } from "@/src/types/places";

export const places: Place[] = [
  {
    id: "1",
    name: "Каньон Мартвили",
    nameEn: "Martvili Canyon",
    lat: 42.4578,
    lng: 42.3772,
    description: "Живописный каньон с лодочными прогулками по реке Абаша.",
    distanceFromTbilisi: 280,
  },
  {
    id: "2",
    name: "Каньон Окаце",
    nameEn: "Okatse Canyon",
    lat: 42.3894,
    lng: 42.5989,
    description: "Подвесная тропа над каньоном, водопады и смотровые площадки.",
    distanceFromTbilisi: 260,
  },
  {
    id: "3",
    name: "Мцхета",
    nameEn: "Mtskheta",
    lat: 41.8458,
    lng: 44.7208,
    description: "Древняя столица, объект ЮНЕСКО: собор Светицховели, монастырь Джвари.",
    distanceFromTbilisi: 25,
  },
  {
    id: "4",
    name: "Крепость Ананури",
    nameEn: "Ananuri Fortress",
    lat: 42.1667,
    lng: 44.7,
    description: "Крепость на Военно-Грузинской дороге у Жинвальского водохранилища.",
    distanceFromTbilisi: 70,
  },
  {
    id: "5",
    name: "Гергети (Троицкая церковь)",
    nameEn: "Gergeti Trinity Church",
    lat: 42.6628,
    lng: 44.6189,
    description: "Храм XIV века на фоне Казбека, символ Грузии.",
    distanceFromTbilisi: 150,
  },
  {
    id: "6",
    name: "Уплисцихе",
    nameEn: "Uplistsikhe",
    lat: 41.9675,
    lng: 44.2067,
    description: "Пещерный город-крепость, один из древнейших в Грузии.",
    distanceFromTbilisi: 90,
  },
  {
    id: "7",
    name: "Вардзия",
    nameEn: "Vardzia",
    lat: 41.3808,
    lng: 43.2844,
    description: "Пещерный монастырский комплекс XII века.",
    distanceFromTbilisi: 270,
  },
  {
    id: "8",
    name: "Боржоми",
    nameEn: "Borjomi",
    lat: 41.8408,
    lng: 43.3839,
    description: "Курортный город, парк и минеральные источники.",
    distanceFromTbilisi: 160,
  },
  {
    id: "10",
    name: "Батуми",
    nameEn: "Batumi",
    lat: 41.6168,
    lng: 41.6367,
    description: "Черноморский курорт, набережная, ботанический сад.",
    distanceFromTbilisi: 380,
  },
];
